config/routes.rb
Fazilai::Application.routes.draw do
  get "/", to: "app#index" , as:'index'
  post "/", to: "authen#login" 

  get "/signup", to: "authen#signup" , as:'singup'
  post "/signup", to: "authen#signupdata"
  get "/logout", to: "authen#logout"

  get "/choose", to: "app#choose" , as:'home'
  post "/choose/createdomain", to: "app#createdomain" ,as:'createdomain'
  post "/choose/loadallserver", to: "app#loadallserver" ,as: "loadallserver"
  post "/choose/deleteserver", to: "app#deleteserver" ,as: 'deleteserver'
  post "/choose/detailserver", to: "app#detailserver" ,as: 'detailserver'
  post "/choose/updateserver", to: "app#updateserver" ,as: 'updateserver'

  post "/choose/loadallproject", to: "app#loadallproject" ,as: 'loadallproject'
  post "/choose/createproject", to: "app#createproject" ,as: 'createproject'
  post "/choose/deleteproject", to: "app#deleteproject" ,as: 'deleteproject'
  post "/choose/detailproject", to: "app#detailproject" ,as: 'detailproject'
  post "/choose/updateproject", to: "app#updateproject" ,as: 'updateproject'

  post "/session", to: "ftp#setsession" , as:'session' 
  get "/server", to: "app#server" , as:'server'
  get "/mkdir" ,to: "ftp#mkdir" ,as: "mkdir"
  get "/mkfile" ,to: "ftp#mkfile" ,as: "mkfile"
  get "/listfile" ,to: "ftp#listfile" ,as: "listfile_root"
  get "/listfile/*dirname" ,to: "ftp#listfile" , as: 'listfile'
  post "/getfile/*dirname" ,to: "ftp#getfile" ,as: "getfile"
  post "/putfile/*dirname" ,to: "ftp#putfile" ,as: "putfile"

  get "/profile", to: "app#profile" , as:'profile' 
  post "/profile", to: "app#profiledata" 
  get "/log", to: "app#log"
  get "/error", to: "app#error" , as:'error' 
end

app/views/app/error.html.erb
<% content_for :include do %>
<% end%>
<% content_for :body do %>
	<style>	
		.errorimg{
			width:500px;
			float:left;
		}
	</style>

	<script>
		$(function(){
			window.setTimeout(function() {
				window.location.href = '/choose';
			}, 2000);
		});
	</script>
	<div style="margin: auto;width: 70%;">
		<%=image_tag("error-e2.png", class: "errorimg")%>
		<div style="padding-top:200px">
			<div style="font-size:70px"><b> Sorry</b> </div>
			<div style="font-size:36px"> Error : <%=@error%></div>
		</div>
	</div>
<% end%>

app/views/app/home.html.erb
<% content_for :navright do %>
	<ul class="nav navbar-nav navbar-right" style="padding-right: 10px">
      <li><%= link_to 'Logout', logout_path() %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li>
	</ul>
<% end %>

app/views/app/index.html.erb
<% content_for :navright do %>
<% end %>

<% content_for :body do %>
	<style>
		@media only screen and (min-width : 1224px) {
			.bg {
				background-image: url(<%= asset_path 'wallpaper.png' %>) !important;
			}
		}
	</style>
	<script>
		$(function(){
			$("#forget").click(function(){
				alert("we will send new password to your mail");

			});	

		});	
	</script>

	<div class="login-box">
	<%= form_for :post do |f| %>

		<% flash.each do |name, msg| -%>
      	<%= content_tag :div, msg, class: name %>
    	<% end %>		

    	<div style="color:white"> New user? <%= link_to 'Sign up', signup_path %> now</div>
    	<%= f.text_field :username ,:class => "form-control fazilai-textform",:placeholder => "e-mail" %><br>
    	<%= f.password_field :password ,:class => "form-control fazilai-textform",:placeholder => "password"%><br>
		<%= f.submit :"sign in" , :class => "form-control fazilai-login btn-warning" , :style => "display:inline"%> 
		<div style="display:inline"> <a id="forget" href="#">forget password?</a></div>
		<br>
		<br>
		<div style="width:300px;height:3px;background:white"><div>
	</div>
	<% end %>
	</div>
<% end%>

app/views/app/log.html.erb
<% content_for :navright do %>
<% end %>

<% content_for :body do %>
	
	<br>
	<center>
	<div class="panel panel-default" style="width:900px">
		<div class="panel-heading">
			<div align="left" style="margin-left: 10px">
				 <h2>Log</h2>
			</div>
		</div>
		<div class="panel-body">

			<%u = Auth.user %>
			<%Log.order(starttime: :desc)%>
			<% logcount=Log.where(user_id: u.id).count %>
			<%a = u.obj.logs.order(starttime: :desc) %>
			

			<!--  
<tr class="active">...</tr>
<tr class="success">...</tr>
<tr class="warning">...</tr>
<tr class="danger">...</tr>
<tr class="info">...</tr>

<tr>
  <td class="active">...</td>
  <td class="success">...</td>
  <td class="warning">...</td>
  <td class="danger">...</td>
  <td class="info">...</td>
</tr>
-->
		
			<table class="table">
			<thead>
				<tr>
					<th>#</th>
					<th>Start Date</th>
					<th>Start Time</th>
					<th>Left Date</th>
					<th>Left Time</th>
					<th>Project</th>
					<th>User</th>
				</tr>
			</thead>
			<tbody>
			<%for i in 0..(logcount-1) %>
				<%if i%2==0%>
				<tr class='active'>
					<td><%=i+1%></td>
					<td><%=a[i][:starttime].to_date.inspect%></td>
					<td><%=a[i][:starttime].strftime("%I:%M %P").inspect%></td>
					<td><%=a[i][:lefttime].to_date.inspect%></td>
					<td><%=a[i][:lefttime].strftime("%I:%M %P").inspect%></td>
					<td><%name1=Proj.where(pid: a[i][:proj_id].inspect).take %><%=name1[:name]%></td>
					<td><%name2=User.where(uid: a[i][:user_id].inspect).take %><%=name2[:email]%></td>
				</tr>
				<%else%>
				<tr class='success'>
				
					<td><%=i+1%></td>
					<td><%=a[i][:starttime].to_date.inspect%></td>
					<td><%=a[i][:starttime].strftime("%I:%M %P").inspect%></td>
					<td><%=a[i][:lefttime].to_date.inspect%></td>
					<td><%=a[i][:lefttime].strftime("%I:%M %P").inspect%></td>
					<td><%name1=Proj.where(pid: a[i][:proj_id].inspect).take %><%=name1[:name]%></td>
					<td><%name2=User.where(uid: a[i][:user_id].inspect).take %><%=name2[:email]%></td>
				</tr>
				<%end%>
			<%end%>
			</tbody>
			</table>
		</div>
	</div>
	</center>
<% end%>

app/views/app/profile.html.erb
<% content_for :body do %>

<style>
	.achieve{
		display: inline-block;
		width: 170px;
		height: 220px;
		border-radius: 30px;
	
		border: 1px solid #A5A518;
		margin-right:5px;
		margin-left:5px;
	}
	.infotab{
		background-color:white;
		float:left;
	}

	legend{
		font-size: 18px;
		margin-top: 10px;
		margin-bottom: 10px;
		color:black;
		border-bottom: none;
		padding-top: 10px;
	}
	.tab-content {
		width:700px;
		margin:auto;
	}
	.tab-content > div{
		height:100%;
		width:700px;
	}
	.nav-tabs{
		width:700px;
		margin:auto;
	}
	.nav-tabs > li.active a{
		background: #fff;
		color: #836F6F;
		width: 120px;
		height: 87px;
		background:none;
		background-image: url(/assets/nav-tab-active.png);
		border:none;
	}
	.nav-tabs > li.active a:hover{
		background: #fff;
		width: 120px;
		height: 87px;
		background:none;
		background-image: url(/assets/nav-tab-active.png);
		border:none;
	}
	.nav-tabs > li a{
		/*color: #fff;*/
		width: 120px;
		height: 87px;

		background:none;
		background-image: url(/assets/normal-tab.png);
		border:none;
	}
	.nav-tabs > li a:hover{
		/*color: #fff;*/
		width: 120px;
		height: 87px;
		background:none;
		background-image: url(/assets/nav-tab.png);
		border:none;
	}

</style>
<script>
	$(function(){
		$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
			var id = $(e.target).attr("href").substr(1);
			localStorage.setItem('selectedTab', id);
			console.log(id)
		});

		var selectedTab = localStorage.getItem('selectedTab');
    	$('#myTab a[href="#' + selectedTab + '"]').tab('show');
		console.log(selectedTab)
	})
</script>


<!-- Nav tabs -->
<ul class="nav nav-tabs" id="myTab">
  <li class="active" ><a href="#profile" data-toggle="tab"  ><br><center>Profile</center></a></li>
  <li><a href="#achievement" data-toggle="tab"><br><center>Achievement</center></a></li>
  <li><a href="#settings" data-toggle="tab"><br><center>Settings</center></a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content" >
	<div class="tab-pane infotab active" id="profile">
		<div align='center' style="color:green">
			<table>
			<tr>
			<td>
			<%u = Auth.user %>
	  		<% result=User.where(uid: u.id).take %>
	  		<legend>&nbsp;&nbsp;&nbsp;&nbsp;Account</legend>
	  		<div style="width:550px;height:1px;background:gray"></div>
	  		<br>

	  			&nbsp;&nbsp;&nbsp;&nbsp;username : 
	   			<%if (result[:email].nil?)==false %>
					<b><i><%=result[:email] %></i></b>
	  			<%else%>
		  			<%="Error query email" %>
				<%end%>
			</td>
			</tr>
			</table>

	   	<table>
		<tr>
		<td>
			<%servercount= Server.where(user_id: u.id).count %><br>
	   		<legend>&nbsp;&nbsp;&nbsp;&nbsp;Server(s) and Project(s)</legend>
	   		<div style="width:550px;height:1px;background:gray"></div><br>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The number of server(s) : <b><i><%=servercount %></i></b><br>
			<br>
			<%s = u.obj.servers  %>
			<%if (s[0].nil?)==false %>
				<%for i in 0..(servercount-1) %>

			<table class="table">
			<tr class="active">
			<td style="width:300px;">				
					 	&nbsp;&nbsp;&nbsp;&nbsp;<%= " Server : "%><%projectcount= Proj.where(server_id: s[i][:sid].inspect).count %><b><i><%=s[i][:name].inspect %></i></b>
			</td>
			<td>		 	
					<%= " contains "%><b><i><%=projectcount%></i></b><%= " project(s)."%>
			</td>
			</tr>
			<tr class="info">
			<td>
					<%if (s[i].projs[0].nil?)==false %>
						<ul>
						<%for ii in 0..(projectcount-1) %>
							<li type=square>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%="	"%><b><%= s[i].projs[ii][:name].inspect%></b>
						<%end%>
						</ul>
					<%else%>
						&nbsp;&nbsp;&nbsp;&nbsp;<%="           No Project(s)"%>
					<% end %>
			<td>
			</tr>
			</table>
				<% end %>

			<%else%>
				&nbsp;&nbsp;&nbsp;&nbsp;<%="No server"%>
			<% end %>
			
			
		</td>
		</tr>
		</table>
		</div>
		
	</div>

	<div class="tab-pane infotab" id="settings">
		<div  align=center>
			<table>
			<tr>
			<td>
				<%= form_for :post do |f| %>
		    		<legend>
						<% flash.each do |name, msg| -%>
				      	<%= content_tag :div, msg, class: name , style:"color:red;font-size:14px" %>
			   	 	<% end %>		
						<div>&nbsp;&nbsp;&nbsp;&nbsp;Change password</div>
					</legend>
					<div style="width:300px;height:1px;background:gray"></div>
					<br>
		    		<%= f.text_field :oldpassword,:class => "form-control fazilai-textform",:placeholder => "old password" %><br>
			    	<%= f.password_field :newpassword ,:class => "form-control fazilai-textform",:placeholder => "new password"%><br>
					<%= f.password_field :renewpassword ,:class => "form-control fazilai-textform",:placeholder => "re new password"%><br>
					&nbsp;&nbsp;&nbsp;&nbsp;<%= f.submit :"Submit" , :class => "form-control fazilai-login btn-warning" , :style => "display:inline"%> 
					<br><br>
				<% end %>
				</td>
			</tr>
			</table>
		</div>
		<br><br>
	</div>

	<div class="tab-pane infotab" id="achievement">
		<div align=center style="color:green">
			<table>
			<tr>
			<td>
			<legend>&nbsp;&nbsp;&nbsp;&nbsp;Achievement(s)</legend>
			<div style="width:550px;height:1px;background:gray"></div>
			<br>
			<% acount=Ownachievement.where(user_id: u.id).count %>
			<%a = u.obj.ownachievements  %>
			<%if (a[0].nil?)== false%>
				<% for i in 0..(acount-1) %>
					<div align='center' class="achieve">
					<div ><br>
							<% ach =  a[i].achievement[:aid].inspect%>		
							<%= image_tag "badge"+ach+".png" %>
    					</div>
    					<p>
      					<span class="name"> 	<%=a[i].achievement[:name].inspect%><br> </span>
        				<span class="created_at"> <%=a[i].achievement[:detail].inspect%> </span>
    					</p>
	  				</div>
					<%if (i+1)%3==0%>
						<br><br>
					<% end %>
				<%end%>
			<%else%>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%="No achievement(s)"%>
			<%end%>
			</td>
			</tr>
			</table>
		</div>
		<br><br>
	</div>


<% end%>

app/views/app/right.html.erb
<% content_for :navright do %>
<div class="collapse navbar-collapse" >
	<ul class="nav navbar-nav navbar-right">
      <li><a href="#">Link</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li>
	</ul>
</div><!-- /.navbar-collapse -->
<% end %>

app/views/app/server.html.erb
<% content_for :include do %>
	<%= javascript_include_tag "server" %>
<% end%>
<% content_for :body do %>
	<!--[if gte IE 9 ]><link rel="stylesheet" type="text/css" href="_styles.css" media="screen"><![endif]-->

	<style>
		.rightdiv{
			/*background-color:red;*/
			float:left;
			width:65%;
			padding-left:40px;
		}
		.leftdiv{
			/*background-color:yellow;*/
			float:left;
			width:320px;
			padding-left:20px;
		}
	</style>

<style type="text/css">
    .CodeMirror {
		height: 500px;
	 }
	.panel-heading{
		height:60px;
	}

	.panel-title{
		font-size: 23px;
		font-weight: bold;
	}

	.btn{
		padding: 6px 12px;
	}
	.edited{
		background-image: url("assets/pencil.png");
		background-size: 15px;
		background-position: right 15px bottom 0px;
		background-repeat: no-repeat;
	}
	.alert{
		background-image: none;
		margin-bottom:0px;
	}

</style>

	<script>
		
		$(function(){

			init_tree("<%= listfile_root_path() %>");
			var te = document.getElementById("code");
			init_editor(te);
		});

	</script>	

<div class="container" style="margin-left:0px">
	<div class="leftdiv">
		<div class="panel panel-default" style="display: inline-block;">
			<div class="panel-heading">
				<h1 class="panel-title" style="float:left"> Directory </h1>
				<div class="btndiv" style="float:right">
					<button type="button" class="btn btn-warning btn-lg" id="createfile" data-toggle="modal" data-target="#modal2">
						<span> <img src=<%= asset_path "icon-createfile.png" %>></span>
					</button>
					<button type="button" class="btn btn-warning btn-lg" id="createfolder" data-toggle="modal" data-target="#modal">
						<span> <img src=<%= asset_path "icon-createfolder.png" %>></span>
					</button>
				</div>
			</div>
			<div class="panel-body roottree" style="padding: 10px 0px 0px 0px;">
				<ol class="tree" > </ol>
			</div>
		</div>
	</div>
	<div class="rightdiv">
		<div class="panel panel-default" style="display: inline-block;position: fixed;width: 760px;">
			<div class="panel-heading">
				<h1 class="panel-title" style="float:left"> Code </h1>
				<div class="btndiv" style="float:right">
					<button type="button" class="btn btn-danger btn-lg" id="savecode">
						<span> <img src=<%= asset_path "icon-save.png" %>></span>
					</button>
				</div>
			</div>
			<div class="panel-body" style="padding: 0px 0px 0px 0px;">
				<textarea id="code" name="code"></textarea>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="mylabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="mylabel">Create Directory</h4>
      </div>
      <div class="modal-body">
      	  	<label class="sr-only" for="newdirectory"> new Directory</label>
				<input type="text" class="form-control" id="newdirectory" placeholder="enter your new directoory">
				<div style="margin-top: 20px;">
	        		<button type="button" class="btn btn-primary" id="createD">Create</button>
   	     		<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
				</div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="mylabel2" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="mylabel2">Create File</h4>
      </div>
      <div class="modal-body">
      	  	<label class="sr-only" for="newfile"> new File</label>
				<input type="text" class="form-control" id="newfile" placeholder="enter your new file">
				<div style="margin-top: 20px;">
	        		<button type="button" class="btn btn-primary" id="createF">Create</button>
   	     		<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
				</div>
      </div>
    </div>
  </div>
</div>

	<% end%>