config/routes.rb
Fazilai::Application.routes.draw do
  get "/", to: "app#index" , as:'index'
  post "/", to: "authen#login" 

  get "/signup", to: "authen#signup" , as:'singup'
  post "/signup", to: "authen#signupdata"
  get "/logout", to: "authen#logout"

  get "/choose", to: "app#choose" , as:'home'
  post "/choose/createdomain", to: "app#createdomain" ,as:'createdomain'
  post "/choose/loadallserver", to: "app#loadallserver" ,as: "loadallserver"
  post "/choose/deleteserver", to: "app#deleteserver" ,as: 'deleteserver'
  post "/choose/detailserver", to: "app#detailserver" ,as: 'detailserver'
  post "/choose/updateserver", to: "app#updateserver" ,as: 'updateserver'

  post "/choose/loadallproject", to: "app#loadallproject" ,as: 'loadallproject'
  post "/choose/createproject", to: "app#createproject" ,as: 'createproject'
  post "/choose/deleteproject", to: "app#deleteproject" ,as: 'deleteproject'
  post "/choose/detailproject", to: "app#detailproject" ,as: 'detailproject'
  post "/choose/updateproject", to: "app#updateproject" ,as: 'updateproject'

  post "/session", to: "ftp#setsession" , as:'session' 
  get "/server", to: "app#server" , as:'server'
  get "/mkdir" ,to: "ftp#mkdir" ,as: "mkdir"
  get "/mkfile" ,to: "ftp#mkfile" ,as: "mkfile"
  get "/listfile" ,to: "ftp#listfile" ,as: "listfile_root"
  get "/listfile/*dirname" ,to: "ftp#listfile" , as: 'listfile'
  post "/getfile/*dirname" ,to: "ftp#getfile" ,as: "getfile"
  post "/putfile/*dirname" ,to: "ftp#putfile" ,as: "putfile"

  get "/profile", to: "app#profile" , as:'profile' 
  post "/profile", to: "app#profiledata" 
  get "/log", to: "app#log"
  get "/error", to: "app#error" , as:'error' 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fazilai</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<style>

		.bg{
		 	background-image: url(<%= asset_path 'bg.png' %>)
		}

		.logo{
			height: 40px;
			position: absolute;
			margin-top: -10px;
		}
		
	</style>
	
	<%= yield :include %>
</head>
<body class="bg" style="padding-top:70px">
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
	 <%= link_to image_tag("logo.png", :class => "logo"), index_path , :class => "navbar-brand" %>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<%
			auth = Auth.user
			if auth.logged
		%>

		<ul class="nav navbar-nav navbar-right" style="padding-right: 10px">
          <li> <%= link_to "Hello! "+auth.name , profile_path %></li>
      	 <li class="dropdown">
        		<a href="#" class="dropdown-toggle" data-toggle="dropdown">Manu <b class="caret"></b></a>
        		<ul class="dropdown-menu">
          		<li> <%= link_to "Profile" , profile_path %></li>
          		<li> <%= link_to "Log" , log_path %></li>
          		<li><a href="#">Donate</a></li>
          		<li class="divider"></li>
					<li><%= link_to 'Logout', logout_path() %></li>
        		</ul>
      	</li>
		</ul>
		<%	end %>
	</div>
</nav>


<%= yield :body %>

</body>
</html>